sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '8'
before_install: npm i -g npm@^5.3.0
script:
- npm start validate
after_success:
- npx codecov@^3
- npx -p semantic-release@6 -c "semantic-release pre && npm publish && semantic-release
  post"
branches:
  only:
  - /.*/
deploy:
  api_key:
    secure: lwScVlyKn606QB57DkpfpXqGP8WSEycQzTcGGkXZNrj7Gf1gQZbbBqVbGoH4Mc6Zqjg8vgZw9XbqMzPSdPXrcWcI5igfoebkAdN/fofIOfRsZUM7+KC4cgm6Van1hCixLZN21ZCzsYq+/imPUTuLogxyE/GgSdKM7tf13MLgN6ccYkaG/sdwtMiclfxZrSbvKEQAJlr3pZp2yb9zHvplmA6w06wea1l3A2O8zDhMiY96lidAz8ykzqInkIGIqdAwlDjX1wX2qEwYuWu/yy89S3ooB3Eal1Ps84dXFLHSNLX44GUwLAJRY25ZlQgf9u54UMYn4URdt0LbI10EkflB9DgNluq9xzZJOzf3xnDeRiVTx0glEdf3n0h4stBzBTmB5jLUZjgenmfwa5ZSM4CHlybMGACGTiNnzd9dZUq5decAaKMueo3qns+hJR8AVm4j3Mc50L7hJ2bayX6P3hMpUgc2mipxub59tecggMYayYw8HIpCj2s0mxstTfJRVNtZzvDZFnJqEPTSsorVf3LPd7eIuW1fnMl7rHjMGXoej4YKpdeNVf5/pWdga1x5iLYpr2cJU/vhXKlELUF1PTC0tvG4JFWO9LFsn1ECordyDr1/hA3d2ayALa7n5l2N5gMz9r3Ml2SXjDrcpCPdor1lxNXnxjyRa+6grXbgtx+zslY=
  provider: npm
  email: "alex@alex-hansen.com"
